//! Deterministic mock providers so the full pipeline runs without API keys.
//! Replace with real implementations behind the same traits.

use async_trait::async_trait;

use crate::providers::{
    estimate_word_timings, AgendaItemDraft, AgendaParser, Exercise, Flashcard, GeneratedContent,
    QuizQuestion, SttProvider, StudyGenerator, Transcript, TranscriptSegment,
};

/// Produces a stable pseudo-transcript proportional to the audio size.
pub struct MockStt;

#[async_trait]
impl SttProvider for MockStt {
    fn name(&self) -> &str {
        "mock-stt"
    }

    async fn transcribe(&self, audio: &[u8]) -> anyhow::Result<Transcript> {
        // ~150 words/minute of speech, ~16 KB/s of compressed audio — enough
        // to make the mock duration look plausible in the admin panel.
        let est_minutes = (audio.len() as f64 / 16_000.0 / 60.0).max(1.0);
        let sentences = (est_minutes as usize).clamp(2, 20);
        let mut text = String::new();
        let mut segments = Vec::with_capacity(sentences);
        for i in 0..sentences {
            let sentence = format!(
                "Point {}: the instructor introduced a concept, illustrated it with an example, \
                 and highlighted the common mistakes to avoid. ",
                i + 1
            );
            text.push_str(&sentence);
            let start_ms = i as i64 * 30_000;
            let end_ms = (i as i64 + 1) * 30_000;
            let segment_text = sentence.trim().to_string();
            segments.push(TranscriptSegment {
                start_ms,
                end_ms,
                words: estimate_word_timings(&segment_text, start_ms, end_ms),
                text: segment_text,
            });
        }
        Ok(Transcript {
            text: text.trim().to_string(),
            language: Some("en".to_string()),
            segments,
        })
    }
}

/// Generates a study pack derived from the chapter title and transcript length.
pub struct MockStudyGenerator;

#[async_trait]
impl StudyGenerator for MockStudyGenerator {
    fn name(&self) -> &str {
        "mock-llm"
    }

    async fn generate(
        &self,
        chapter_title: &str,
        transcript: &Transcript,
    ) -> anyhow::Result<GeneratedContent> {
        let words = transcript.text.split_whitespace().count();

        let summary_markdown = format!(
            "# {chapter_title} — Summary\n\n\
             > Generated by `{}` from a transcript of ~{} words.\n\n\
             ## Key ideas\n\n\
             - Core concept introduced in this chapter: **{chapter_title}**.\n\
             - The lesson walked through definitions, worked examples, and pitfalls.\n\n\
             ## What to remember\n\n\
             1. Restate the main concept in your own words.\n\
             2. Re-do the worked example without looking at your notes.\n\
             3. List two common mistakes and how to avoid them.\n\n\
             ## Suggested next step\n\n\
             Attempt the exercises below, then test yourself with the quiz.",
            self.name(),
            words
        );

        let exercises = vec![
            Exercise {
                prompt: format!("Summarize the goal of “{chapter_title}” in two sentences."),
                guidance: Some("Focus on the *why*, not just the *what*.".into()),
                answer: None,
            },
            Exercise {
                prompt: "Recreate the main worked example from this chapter without notes.".into(),
                guidance: Some(
                    "If you get stuck, re-listen to the middle third of the recording.".into(),
                ),
                answer: None,
            },
            Exercise {
                prompt:
                    "Write down three questions you think an exam could ask about this chapter."
                        .into(),
                guidance: None,
                answer: None,
            },
        ];

        let quiz = vec![
            QuizQuestion {
                prompt: format!("What is the central topic of this chapter?"),
                topic: Some(chapter_title.to_string()),
                choices: vec![
                    chapter_title.to_string(),
                    "An unrelated elective topic".into(),
                    "Administrative announcements".into(),
                    "None of the above".into(),
                ],
                correct_index: 0,
                explanation: Some("The chapter recording covers its own title topic.".into()),
            },
            QuizQuestion {
                prompt: "According to the summary, what should you do after studying?".into(),
                topic: Some("Méthode de révision".into()),
                choices: vec![
                    "Skip practice and move on".into(),
                    "Attempt the exercises, then take the quiz".into(),
                    "Delete your notes".into(),
                    "Only re-read the transcript".into(),
                ],
                correct_index: 1,
                explanation: Some("Active recall beats passive re-reading.".into()),
            },
            QuizQuestion {
                prompt: "How were common mistakes handled in this lesson?".into(),
                topic: Some("Erreurs fréquentes".into()),
                choices: vec![
                    "They were ignored".into(),
                    "They were highlighted and discussed".into(),
                    "They were left as homework only".into(),
                    "They were not mentioned".into(),
                ],
                correct_index: 1,
                explanation: None,
            },
        ];

        Ok(GeneratedContent {
            summary_markdown,
            key_points: vec![
                format!("Comprendre le concept central de {chapter_title}."),
                "Savoir refaire l'exemple principal sans les notes.".into(),
                "Identifier les erreurs fréquentes et les éviter.".into(),
            ],
            takeaway: Some(format!(
                "La maîtrise de {chapter_title} vient de la pratique active, pas seulement de la relecture."
            )),
            flashcards: vec![
                Flashcard {
                    front: format!("Quel est l'objectif de {chapter_title} ?"),
                    back: "Expliquer le concept central et l'appliquer à un exemple.".into(),
                },
                Flashcard {
                    front: "Quelle est la meilleure étape suivante ?".into(),
                    back: "Refaire l'exemple, puis répondre au quiz sans consulter les notes.".into(),
                },
            ],
            exercises,
            quiz,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn mock_stt_produces_transcript() {
        let stt = MockStt;
        assert_eq!(stt.name(), "mock-stt");

        // Simulate ~5 minutes of audio (5 * 60 * 16_000 bytes)
        let audio = vec![0u8; 5 * 60 * 16_000];
        let transcript = stt.transcribe(&audio).await.unwrap();

        assert!(!transcript.text.is_empty());
        assert!(!transcript.segments[0].words.is_empty());
        assert_eq!(transcript.language, Some("en".to_string()));
        assert!(transcript.text.contains("Point 1:"));
        assert!(transcript.text.contains("Point 5:"));
        assert_eq!(transcript.segments.len(), 5);
    }

    #[tokio::test]
    async fn mock_stt_clamps_minimum_sentences() {
        let stt = MockStt;
        // Very small audio (less than 1 minute)
        let audio = vec![0u8; 100];
        let transcript = stt.transcribe(&audio).await.unwrap();
        // Should still produce at least 2 sentences (the clamp minimum)
        assert!(transcript.text.contains("Point 1:"));
        assert!(transcript.text.contains("Point 2:"));
    }

    #[tokio::test]
    async fn mock_stt_clamps_maximum_sentences() {
        let stt = MockStt;
        // Very large audio (100 minutes)
        let audio = vec![0u8; 100 * 60 * 16_000];
        let transcript = stt.transcribe(&audio).await.unwrap();
        // Should not exceed 20 sentences
        assert!(transcript.text.contains("Point 20:"));
        assert!(!transcript.text.contains("Point 21:"));
    }

    #[tokio::test]
    async fn mock_generator_produces_all_sections() {
        let gen = MockStudyGenerator;
        assert_eq!(gen.name(), "mock-llm");

        let transcript = Transcript {
            text: "This is a test transcript with several words in it.".to_string(),
            language: Some("en".to_string()),
            segments: vec![],
        };

        let content = gen.generate("Linear Algebra", &transcript).await.unwrap();

        // Summary includes the chapter title
        assert!(content.summary_markdown.contains("Linear Algebra"));
        assert!(content.summary_markdown.contains("Summary"));

        // 3 exercises
        assert_eq!(content.exercises.len(), 3);
        assert!(content.exercises[0].prompt.contains("Linear Algebra"));

        // 3 quiz questions
        assert_eq!(content.quiz.len(), 3);
        for q in &content.quiz {
            assert!(!q.choices.is_empty());
            assert!(q.correct_index >= 0);
            assert!((q.correct_index as usize) < q.choices.len());
        }
    }

    #[tokio::test]
    async fn mock_generator_quiz_has_valid_choices() {
        let gen = MockStudyGenerator;
        let transcript = Transcript {
            text: "Some content here.".to_string(),
            language: None,
            segments: vec![],
        };

        let content = gen.generate("Test Chapter", &transcript).await.unwrap();

        for q in &content.quiz {
            assert!(
                q.choices.len() >= 2,
                "each question needs at least 2 choices"
            );
            assert!(
                (q.correct_index as usize) < q.choices.len(),
                "correct_index must be within choices"
            );
        }
    }

    #[tokio::test]
    async fn mock_generator_exercises_have_guidance() {
        let gen = MockStudyGenerator;
        let transcript = Transcript {
            text: "Words.".to_string(),
            language: None,
            segments: vec![],
        };

        let content = gen.generate("Chapter", &transcript).await.unwrap();

        // At least some exercises should have guidance
        let with_guidance = content
            .exercises
            .iter()
            .filter(|e| e.guidance.is_some())
            .count();
        assert!(
            with_guidance > 0,
            "at least one exercise should have guidance"
        );
    }
}

/// Canned agenda parser for offline development. Returns three sample
/// items so the mobile confirmation screen has something to show.
pub struct MockAgendaParser;

#[async_trait::async_trait]
impl AgendaParser for MockAgendaParser {
    fn name(&self) -> &str {
        "mock-agenda"
    }

    async fn parse(&self, _input: &[u8]) -> anyhow::Result<Vec<AgendaItemDraft>> {
        // Deterministic mock — doesn't read the bytes. The mobile sees
        // the same three items every time it scans in mock mode.
        Ok(vec![
            AgendaItemDraft {
                title: "Mathématiques — Algèbre".into(),
                starts_at: Some("2026-08-25T09:00:00+00:00".into()),
                ends_at: Some("2026-08-25T10:00:00+00:00".into()),
                notes: Some("Salle B204".into()),
            },
            AgendaItemDraft {
                title: "Français — Dissertation".into(),
                starts_at: Some("2026-08-26T14:00:00+00:00".into()),
                ends_at: Some("2026-08-26T15:30:00+00:00".into()),
                notes: None,
            },
            AgendaItemDraft {
                title: "Histoire — Révision chapitre 3".into(),
                starts_at: Some("2026-08-27T10:00:00+00:00".into()),
                ends_at: None,
                notes: Some("Apporter le manuel".into()),
            },
        ])
    }
}
