[package]
name = "buddywize-admin"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
buddywize-auth.workspace = true
buddywize-core.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true
